### ISSUE TITLE
Can no longer download as .html

### ISSUE THREAD

**Issue by chrisrb10** [jupyter/nbconvert#744]
I recently upgraded Jupyter notebook from 5.0.0 to 5.1.0 (using Conda). And now I can't download a notebook as .html (which I do a lot).
It used to work (with 5.0.0) - but if I try now I get the message:
**500: Internal Server Error**
`Could not import nbconvert: No module named 'nbconvert.exporters.base`

Any idea how to get the download as html working again?

**Comment by chrisrb10** [comment]
btw - if I downgrade back to 5.0.0 (with conda) the download to html works again. But would be good to have it working with the up to date version.

**Comment by mpacer** [comment]
Did you try upgrading both nbconvert and notebook? Not finding the
nbconvert.exporters.base module suggests you have a fairly old version of
nbconvert.

**Comment by chrisrb10** [comment]
thank @mpacer 
nbconvert was 4.2.0. I upgraded to 5.3.1 (which also triggered me to reinstall jsonschema (`conda install -c anaconda jsonschema` ) to get jupyter notebook to work.

Unfortunately, download to html doesn't seem to work at all. I get the following:

```
[E 10:36:14.732 NotebookApp] nbconvert failed: validate() got an unexpected keyword argument 'relax_add_props'
    Traceback (most recent call last):
      File "/Users/Chris/anaconda3/lib/python3.6/site-packages/notebook/nbconvert/handlers.py", line 122, in get
        resources=resource_dict
      File "/Users/Chris/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/html.py", line 85, in from_notebook_node
        return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
      File "/Users/Chris/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 280, in from_notebook_node
        nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
      File "/Users/Chris/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/Users/Chris/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 313, in _preprocess
        nbformat.validate(nbc, relax_add_props=True)
    TypeError: validate() got an unexpected keyword argument 'relax_add_props'
[W 10:36:14.748 NotebookApp] 500 GET /nbconvert/html/Google%20Drive/DATA%20SCIENCE/coursera/applied_machine_learning/Assign4_CB_submission-V2.ipynb?download=true (::1): nbconvert failed: validate() got an unexpected keyword argument 'relax_add_props'
```
This happens in the notebook 5.0.0 I was using, and also if I upgrade to the latest version (5.3.1).

I use download to .html a lot - so this is now quite a problem. Any ideas?

**Comment by takluyver** [comment]
Try upgrading the `nbformat` package too.

**Comment by chrisrb10** [comment]
thanks @takluyver - that did it.
`conda install nbformat` updated it from 4.2.0 to 4.4.0
And now works fine with jupyter notebook 5.3.1

**Comment by takluyver** [comment]
Great. We're already specifying the necessary version of nbformat, so I'll close this issue.

https://github.com/jupyter/nbconvert/blob/5f5ae49bdefc07c4bba9a6215a3f5d00fcf75ab5/setup.py#L193

**Comment by paula-santos** [comment]
Hi,
I am having the same problem, but updating nbformat did not help.
Now I am using nbformat 4.4.0 and notebook 5.4.0.
When I choose fine > download as > html, I get:

500 : Internal Server Error
The error was: Could not import nbconvert: No module named base

Any ideas of what might be going on?

Thanks a lot!

**Comment by takluyver** [comment]
What version of nbconvert have you got installed?

**Comment by paula-santos** [comment]
Hi Takluyver, thanks for your reply!
I'm using nbconvert 5.3.1

**Comment by takluyver** [comment]
That's the latest version, and it definitely should have the [nbconvert.exporters.base module](https://github.com/jupyter/nbconvert/blob/5.3.1/nbconvert/exporters/base.py). The only thing I can suggest is to uninstall and reinstall it.

**Comment by FENGSHAN95** [comment]
I have also the same problem as Paula-santos even after uninstall and reinstall the nbconvert. But we CAN manually import 'nbconvert.exporters.base' module.

**Comment by mpacer** [comment]
Are you launching your server with the same python environment that you’re
using to check to see whether you can import `nbconvert.exporters.base`? If
you have more than one python environment (e.g., because you are using
anaconda or virtual env) you might have access to different versions of
those packages in different environments.

Try running `python -c 'import nbconvert; print(nbconvert.__version__)'`,
then, what version of nbconvert is printed?

Cheers,
M

**Comment by bioqubs** [comment]
I solve this by reviewing the official page of nbcovert https://nbconvert.readthedocs.io, where the installation needs pandoc and TeX, so:

```
pip install nbconvert  / conda install nbconvert 
sudo apt-get install pandoc
sudo apt-get install texlive-xetex 
```

In this case, when I (re)installed texlive-xetex, the error was gone and I was abled to download the pdf file. 
I prove it with html and download too!

**Comment by FENGSHAN95** [comment]
I solved this problem by upgrading nbconverter and nbformat in all the environments I have.

**Comment by hugo-pires** [comment]
The option "Download as" is not available any more. I don't get any kind of error
